### ISSUE TITLE
Mace Durability Bug

### ISSUE THREAD

**Issue by RogueEnderman** [Provismet/Additional-Armoury#2]
### Type of Error

Incorrect Behaviour

### Description

Unlike the other weapons and tools in this mod, maces (of all kinds) no not lose durability upon use.

### Mod Version

1.0.0+1.20.1 Fabric/Quilt

### Minecraft Version

1.20.1

### Mod Loader

Fabric, Quilt

### Steps to Reproduce

- Give yourself or craft any mace from this mod
- Use it to attack a mob
- The item will not be damaged

**Comment by Provismet** [comment]
This is now fixed as of the 1.0.1 patch.
