### ISSUE TITLE
1.21 Missing Translations

### ISSUE THREAD

**Issue by makumaku1974** [Provismet/Additional-Armoury#6]
### Type of Error

Other

### Description

Missing Translations

### Mod Version

2.0.0

### Minecraft Version

1.21

### Mod Loader

Fabric

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/708b9390-ed96-494b-a940-74b189b0895f)

**Comment by Provismet** [comment]
Scorching? I've never heard of this potion effect, is it from another mod?

**Comment by makumaku1974** [comment]
Ohhh it's from Wilder Wilds which is a great mod. Should i report this to them too?

This is from Contagion
![image](https://github.com/user-attachments/assets/b3cb9dd1-165f-4815-8eac-525e1701124b)

This is from Stamina Tweakers
![image](https://github.com/user-attachments/assets/a83400ea-30d2-44ce-841e-4993f023938f)
![image](https://github.com/user-attachments/assets/131baac8-9a67-4e79-b0f2-0ffbcf16b7df)

**Comment by Provismet** [comment]
That's the reason for the missing translation. Translation keys are not automatic, each one must be manually added.  
In other words, although daggers are compatible with modded potions, unless someone manually adds a translation for it, it will just show the key.

This isn't a bug on either side. My advice would be to create your own resourcepack for your modpack with the translation keys added.  
You could also try sending this report to the other mod developers in hopes that they'll add keys for you, but understand that most probably aren't too interested in adding dozens of translation keys for this.

**Comment by makumaku1974** [comment]
okay okay got it. Is there a way for you to tell me what I should do when customizing it using resourcepacks? I'm quite a newbie when it comes to coding it let alone figuring out translation errors.

**Comment by Provismet** [comment]
Sure, resourcepacks are honestly very simple though. They aren't code at all.
You just need to create a a lang file to provide translation keys.

1. Create a new folder (this folder will be the resoucepack itself).
2. Add a `pack.mcmeta` file to your folder. You can check the wiki for the for the format (or just copy one from an existing resourcepack and change the name/description).
3. Add a new path of folders: assets -> name_of_your_pack -> lang
  a. The name doesn't matter as long as it's all lowercase with no spaces.
4. Inside lang make a new file `en_us.json` (or whatever language you want, `en_gb` would be the far superior British English, for example)
5. Add your translation key, format looks like [this](https://github.com/Provismet/Additional-Armoury/blob/1.21/src/main/generated/assets/additional-armoury/lang/en_us.json).

**Comment by makumaku1974** [comment]
It kinda looks tiring to look at but holy still going to do it though.

**Comment by NathanX-S** [comment]
@Provismet Wouldn't it make more sense to automatically create these names using a "base name" from your mod and then concating the name of the effect from the other mod/base game?

**Comment by Provismet** [comment]
No, that's not how this works.

Translation keys are converted into names via a resourcepack; I [can and do](https://github.com/Provismet/Additional-Armoury/blob/1.21/src/main/java/com/provismet/datagen/AdditionalArmoury/LanguageGenerator.java#L152) automatically generate names in English; this does not happen in real-time and is only used to generate the built-in resourcepack. I cannot do this for modded potions, it is up to modpack makers or other modders to add those additional keys.
